NAME		=	libft.a

PATH_SRCS	=	./srcs/

SRCS		=	/rcs/ft_putchar.c /rcs/ft_swap.c srcs/ft_putstr.c srcs/ft_strlen.c srcs/ft_strcmp.c

INCLUDES	=	./includes

OBJS		=	${SRCS:.c=.o}

RM			= rm -f

CFLAGS		= -Wall -Wextra -Werror

all:		${NAME}

.c.o:
			${CC} -c ${CFLAGS} -I ${INCLUDES} $< -o ${<:.c=.o}

${NAME}:	${OBJS}
			ar rc ${NAME} ${OBJS}

clean:
			${RM} ${OBJS}

fclean:		clean
			${RM} ${NAME}

re:			fclean all

.PHONY:		all clean fclean re
